language: node_js
node_js:
  - 12

cache:
  apt: true
  yarn: true
  directories:
    - node_modules

before_install:
  - export TZ=Asia/Taipei

jobs:
  include:
    - stage: build
      if: branch != develop
      script:
        - npm run lint
        - npm install
        - npm run build
    - stage: deploy
      if: branch = develop
      script:
        # Decrypt the private key
        - openssl aes-256-cbc -K $encrypted_d7634ff77415_key -iv $encrypted_d7634ff77415_iv -in .travis/ssh_key.enc -out ~/.ssh/id_rsa -d
        # Set the permission of the key
        - chmod 600 ~/.ssh/id_rsa
        # Start SSH agent
        - eval $(ssh-agent)
        # Add the private key to the system
        - ssh-add ~/.ssh/id_rsa
        # Copy SSH config
        - cp .travis/ssh_config ~/.ssh/config
        # Set Git config
        - git config --global user.name "bot"
        - git config --global user.email ssarcandy@gmail.com 
        - git clone https://github.com/SSARCandy/ssarcandy.github.io .deploy_git
        - cd .deploy_git && git checkout master
        - cd ..
        - npm run lint
        - npm run build:pageview
        - npm run build:webpack
        - npm run deploy
