# hexo-theme-indigo
# https://github.com/yscoder/hexo-theme-indigo

#添加新菜单项遵循以下规则
# menu:
#  link:               fontawesome or material-icon 图标
#    type: 'fa' / 'ml' 哪個系列的圖示 
#    text: About       菜单显示的文字，如果省略即默认与图标一致，首字母会转大写
#    url: /about       链接，绝对或相对路径，必须。
#    target: _blank    是否跳出，省略则在当前页面打开
menu:
  person:
    type: ml
    text: About
    url: /about
  description:
    type: ml
    text: Posts
    url: /
    # turbo: false
  view_list:
    type: ml
    text: Archives
    url: /archives
  code:
    type: ml
    text: Projects
    url: /projects
  github:
    type: fa
    url: https://github.com/SSARCandy
    target: _blank

social_links:
  email:
    url: mailto:ssarcandy@gmail.com
    icon: icon-envelope-square
    target: 
  linkedin:
    url: https://www.linkedin.com/in/ssarcandy
    icon: icon-linkedin-square
    target: _blank
  twitter:
    url: https://twitter.com/ssarcandy
    icon: icon-twitter-square
    target: _blank
  github:
    url: https://github.com/SSARCandy
    icon: icon-github-square
    target: _blank

rss: /atom.xml

#你的头像url
avatar: /img/logo.png

# email
email: ssarcandy@gmail.com

motto: There is always more than one solution.

# 设置 Android L Chrome 浏览器状态栏颜色
color: '#673AB7'

# Content
tags:
  title: 標籤

excerpt_link: more
mathjax: false
archive_yearly: true

#是否开启分享
share: false

#是否开启搜索
search: true

#是否啟用 turbolinks.js (issue #21)
turbolinks: false 

#是否大屏幕下文章页隐藏导航
hideMenu: true

adsense: false

#是否开启toc
#toc: true
toc:
  list_number: false  # 是否显示数字排序


# Miscellaneous
google_analytics: 'UA-81178870-1'
favicon: /img/favicon.ico

# less
less:
  paths:
    - source/css/style.less

# swipe guesture using hammer.js
swipe_guesture: false