# menu:
#  link:               Material Icons ligature name (https://fonts.google.com/icons).
#    text: About       The label show on menu (using :lang.yml file).
#    url: /about       Link url
#    target: _blank    Open new tab or not
menu:
  person:
    text: menu.about
    url: /about
  description:
    text: menu.post
    url: /
    # turbo: false
  view_list:
    text: menu.archive
    url: /archives
  photo_camera:
    text: menu.photography
    url: /photography
  code:
    text: menu.project
    url: /projects

social_links:
  email:
    url: mailto:ssarcandy@gmail.com
    icon: icon-envelope-square
    target: 
  github:
    url: https://github.com/SSARCandy
    icon: icon-github-square
    target: _blank
  flickr:
    url: https://www.flickr.com/photos/200681089@N06/
    icon: icon-flickr
    target: _blank
    user_id: 200681089@N06
  rss:
    url: /atom.xml
    icon: icon-rss-square
    target: _blank

rss: /atom.xml
avatar: /img/logo.png
email: ssarcandy@gmail.com
motto: There is always more than one solution.

# Android Chrome status bar color
color: '#673AB7'

# Content
tags:
  title: 標籤

excerpt_link: more
archive_yearly: true
share: true
search: true

# Use turbolinks.js (issue #21)
turbolinks: false 

# Hide menus when screen width is wide
hideMenu: true

adsense:
  enable: true
  slot:
    post_bottom: true
    post_toc: false
    archive_list: false

#toc: true
toc:
  list_number: false 

# Miscellaneous
google_analytics: 'G-4YMNTX9S2Q'
favicon: /img/favicon.ico

# less
less:
  paths: ['source/css/style.less']

# swipe guesture using hammer.js
swipe_guesture: false

disqus_shortname: ssarcandy
