# menu:
#  link:               fontawesome or material-icon.
#    type: 'fa' / 'ml' Icon set. fa => font-awesome, ml => material design
#    text: About       The label show on menu (using :lang.yml file).
#    url: /about       Link url
#    target: _blank    Open new tab or not
menu:
  person:
    type: ml
    text: menu.about
    url: /about
  description:
    type: ml
    text: menu.post
    url: /
    # turbo: false
  view_list:
    type: ml
    text: menu.archive
    url: /archives
  code:
    type: ml
    text: menu.project
    url: /projects
  github:
    type: fa
    text: menu.github
    url: https://github.com/SSARCandy
    target: _blank

social_links:
  email:
    url: mailto:ssarcandy@gmail.com
    icon: icon-envelope-square
    target: 
  linkedin:
    url: https://www.linkedin.com/in/ssarcandy
    icon: icon-linkedin-square
    target: _blank
  twitter:
    url: https://twitter.com/ssarcandy
    icon: icon-twitter-square
    target: _blank
  github:
    url: https://github.com/SSARCandy
    icon: icon-github-square
    target: _blank

rss: /atom.xml
avatar: /img/logo.png
email: ssarcandy@gmail.com
motto: There is always more than one solution.

# Android Chrome status bar color
color: '#673AB7'

# Content
tags:
  title: 標籤

excerpt_link: more
mathjax: true
archive_yearly: true
share: true
search: true

# Use turbolinks.js (issue #21)
turbolinks: false 

# Hide meus when screen width is wide
hideMenu: true

adsense:
  enable: true
  slot:
    post_bottom: true
    post_toc: false
    archive_list: false

#toc: true
toc:
  list_number: false 

# Miscellaneous
google_analytics: 'UA-81178870-1'
favicon: /img/favicon.ico

# less
less:
  paths:
    - source/css/style.less

# swipe guesture using hammer.js
swipe_guesture: false
